### ISSUE TITLE
Vortex-IDS problem compiling

### ISSUE THREAD

**Issue by Keskebeu** [lmco/vortex-ids#5]
Hello,

I have been trying to compile vortex-ids but i get the following problems. I have linux mint serena cinamon 64 bit. I have downloaded vortex and while trying to compile it with gcc i get the following problems:

gcc vortex.c -lnids -lpthread -Wall -o vortex
/usr/bin/ld: /tmp/ccxrNS7u.o: undefined reference to symbol 'pcap_stats'
//usr/lib/x86_64-linux-gnu/libpcap.so.0.8: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

I used the command : vortex # gcc vortex.c -lnids -lpthread -Wall -o vortex.

I also tried to compile it with c++ and g++ but i get the following:

vortex # g++ vortex.c -lnids -lpthread -Wall -o vortex
vortex.c:37:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
vortex.c:111:21: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
 char *temp_data_dir="";
                     ^
vortex.c:164:20: error: aggregate ‘error_stats errors’ has incomplete type and cannot be defined
 struct error_stats errors;
                    ^
vortex.c: In function ‘void tcp_callback(tcp_stream*, conn_param**)’:
vortex.c:1156:60: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if ((last_timestamp - tcp_head->last_activity) > tcp_max_idle)
                                                            ^
vortex.c:1207:26: error: invalid conversion from ‘void*’ to ‘conn_param*’ [-fpermissive]
             a_conn=calloc(1,sizeof(struct conn_param));
                          ^
vortex.c:1329:51: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
                 a_conn->to_client_data_p = realloc(a_conn->to_client_data_p,a_conn->to_client_buffer_size);
                                                   ^
vortex.c:1402:51: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
                 a_conn->to_server_data_p = realloc(a_conn->to_server_data_p,a_conn->to_server_buffer_size);
                                                   ^
vortex.c: In function ‘int main(int, char**)’:
vortex.c:1484:18: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     logging_name = "Vortex";
                  ^
vortex.c:1737:32: error: invalid conversion from ‘void (*)()’ to ‘void (*)(int, int, ip*, void*)’ [-fpermissive]
     libnids_syslog=nids_params.syslog;
                                ^
vortex.c:1738:23: error: invalid conversion from ‘void (*)(int, int, ip*, void*)’ to ‘void (*)()’ [-fpermissive]
     nids_params.syslog=vortex_nids_syslog;
                       ^
vortex.c:1999:35: error: invalid conversion from ‘void (*)(tcp_stream*, conn_param**)’ to ‘void*’ [-fpermissive]
     nids_register_tcp(tcp_callback);
                                   ^
In file included from vortex.c:60:0:
/usr/include/nids.h:147:6: note:   initializing argument 1 of ‘void nids_register_tcp(void*)’
 void nids_register_tcp (void (*));

I have downloaded the following packages $ sudo apt-get install libnids-dev libnet-dev libpcap-dev.

Any help would be appreciable. Thank you.

**Comment by marnao** [comment]
perhaps try including -lpcap in your command?

**Comment by Keskebeu** [comment]
Thank you very much for the fast reply, I was able to compile it. -lpcap was what I was missing. Wish you best.
